# Generated by Django 6.0 on 2025-12-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isnb", models.TextField(default=None, null=True, unique=True)),
                ("name", models.TextField(unique=True)),
                ("author", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("release_year", models.DateField()),
                ("genre", models.ManyToManyField(to="app.genre")),
                ("product_urls", models.ManyToManyField(to="app.producturl")),
            ],
        ),
    ]
