# Generated by Django 6.0 on 2025-12-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
