# Generated by Django 6.0 on 2025-12-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
