# Generated by Django 6.0 on 2025-12-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_book_name_alter_book_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isnb',
            field=models.TextField(null=True, unique=True),
        ),
    ]
