# Generated by Django 6.0 on 2025-12-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isnb',
            new_name='isbn',
        ),
    ]
